# Generated by Django 6.0.3 on 2026-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
