# Generated by Django 6.0.3 on 2026-03-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donation_address_donation_image_url_donation_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points_threshold', models.IntegerField()),
                ('reward_bonus', models.IntegerField(default=0)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('role_target', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='food_type',
            new_name='food_category',
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='total_donations',
            new_name='total_donations_value',
        ),
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='vehicle',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='phone',
        ),
        migrations.AddField(
            model_name='donation',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_items',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='tracking_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='donation',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='ngo_type',
            field=models.CharField(default='Social Service', max_length=100),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='claim_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='donation',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ONBOARDING', 'Registration/Onboarding'), ('REWARD', 'Reward Claim/Points'), ('PROFILE', 'Profile Update'), ('TECHNICAL', 'Technical Issue'), ('DONATION', 'Donation Related')], max_length=20)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGOInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='In Stock', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('source_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.donation')),
            ],
        ),
        migrations.CreateModel(
            name='NGONeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(default='Normal', max_length=20)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.donation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
