# Generated by Django 6.0.3 on 2026-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donation_contact_phone_bankaccount_upiidentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image_url',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
