# Generated by Django 6.0.3 on 2026-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_donation_image_url_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
