# Generated by Django 6.0.3 on 2026-04-02 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_donation_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='related_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_donations', to='api.ngoneed'),
        ),
    ]
