# Generated by Django 6.0.3 on 2026-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_points_donorprofile_donation_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoneed',
            old_name='title',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='beneficiaries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='distribution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='needs/'),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='unit',
            field=models.CharField(default='Units', max_length=20),
        ),
        migrations.AlterField(
            model_name='ngoneed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ngoneed',
            name='urgency',
            field=models.CharField(default='Medium Priority', max_length=20),
        ),
    ]
