# Generated by Django 6.0.3 on 2026-04-06 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_badge_icon_rewardtier_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckySpinPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('NGO', 'NGO'), ('VOLUNTEER', 'Volunteer')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('prize_type', models.CharField(choices=[('CASH', 'Cash Reward'), ('GRANT', 'Grand Grant'), ('POINTS', 'Points Bonus'), ('BADGE', 'Exclusive Badge')], default='CASH', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('probability', models.FloatField(default=0.1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LuckySpinDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_spins', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.luckyspinprize')),
            ],
        ),
    ]
