# Generated by Django 6.0.3 on 2026-04-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_ngo_type_ngoprofile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='lifetime_points',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='service_areas',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='vision',
        ),
    ]
