# Generated by Django 6.0.3 on 2026-04-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_donation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='assigned_volunteer',
        ),
        migrations.AddField(
            model_name='donation',
            name='accepted_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
