# Generated by Django 6.0.3 on 2026-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ngoneed_accepted_at_ngoneed_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoneed',
            name='donor_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='fulfilled_quantity',
            field=models.FloatField(default=0),
        ),
    ]
