# Generated by Django 6.0.3 on 2026-04-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_ngoneed_donor_ids_ngoneed_fulfilled_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoneed',
            name='beneficiaries',
        ),
    ]
