# Generated by Django 6.0.3 on 2026-04-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_donor_ids_ngoneed_supporter_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='related_need',
        ),
    ]
