# Generated by Django 6.0.3 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_ngoprofile_donation_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('NGO', 'NGO'), ('VOLUNTEER', 'Volunteer')], default='NGO', max_length=20),
        ),
    ]
