# Generated by Django 6.0.3 on 2026-04-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_reward_amount_reward_available_reward_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='provider',
        ),
    ]
