# Generated by Django 6.0.3 on 2026-04-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_badge_rewardtier_donorprofile_lifetime_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('action_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='earning_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
