# Generated by Django 6.0.3 on 2026-04-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rewardconfiguration_rewardtier_earning_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardtier',
            name='benefits',
        ),
    ]
