# Generated by Django 6.0.3 on 2026-04-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_rewardtier_benefits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='reward_points',
        ),
    ]
