# Generated by Django 6.0.3 on 2026-04-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_category_categorysuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysuggestion',
            name='admin_notes',
        ),
    ]
