# Generated by Django 6.0.3 on 2026-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_categorysuggestion_admin_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoinventoryitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ngoinventoryitem',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoinventoryitem',
            name='item_condition',
            field=models.CharField(default='Excellent', max_length=100),
        ),
        migrations.AddField(
            model_name='ngoinventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngoinventoryitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
