# Generated by Django 6.0.3 on 2026-04-06 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_added_at_ngoinventoryitem_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardtier',
            old_name='badge_icon',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='rewardtier',
            name='earning_bonus',
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='bonus_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('NGO', 'NGO'), ('VOLUNTEER', 'Volunteer')], default='NGO', max_length=10),
        ),
    ]
