# Generated by Django 6.0.3 on 2026-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_donation_related_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='donation_points',
            field=models.IntegerField(default=0),
        ),
    ]
