# Generated by Django 6.0.3 on 2026-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_reward_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
