# Generated by Django 6.0.3 on 2026-04-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_contact_person_donorprofile_primary_manager_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='points',
            new_name='donation_points',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='lifetime_points',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='total_donations_value',
        ),
    ]
