# Generated by Django 6.0.3 on 2026-04-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_informationupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='active_needs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='beneficiaries_helped_count',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='managing_director_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='managing_director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='official_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='operating_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='tax_exemption_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='total_donations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NGODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('80G_CERTIFICATE', 'Tax Exempt Certificate (80G)'), ('OPERATING_LICENSE', 'Operating License'), ('NGO_REGISTRATION', 'NGO Registration'), ('TRUST_DEED', 'Trust Deed'), ('OTHER', 'Other')], max_length=50)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ngo_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.ngoprofile')),
            ],
        ),
    ]
