# Generated by Django 6.0.3 on 2026-04-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_ngoprofile_active_needs_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='ngo_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='managing_director_name',
            new_name='managing_director',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='operating_office_address',
            new_name='office_address',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='registration_no',
            new_name='registration_id',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='tax_exemption_id',
            new_name='tax_id',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='official_website',
            new_name='website',
        ),
    ]
