# Generated by Django 6.0.3 on 2026-04-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_ngoneed_beneficiaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoneed',
            old_name='donor_ids',
            new_name='supporter_ids',
        ),
    ]
