# Generated by Django 6.0.3 on 2026-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_reward_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
